
distribution_version = "jammy"
architecture = "arm64"
folder = "rpi-ubuntu-arm64-sysroot"

packages = [
    "python3-colcon-ros",
    "python3-rosdep-modules",
    "python3-rosdep",
    "python3-rosdistro-modules",
    "python3-rospkg-modules",
    "ros-rolling-action-msgs",
    "ros-rolling-action-tutorials-cpp",
    "ros-rolling-action-tutorials-interfaces",
    "ros-rolling-action-tutorials-py",
    "ros-rolling-actionlib-msgs",
    "ros-rolling-ament-cmake-auto",
    "ros-rolling-ament-cmake-copyright",
    "ros-rolling-ament-cmake-core",
    "ros-rolling-ament-cmake-cppcheck",
    "ros-rolling-ament-cmake-cpplint",
    "ros-rolling-ament-cmake-export-definitions",
    "ros-rolling-ament-cmake-export-dependencies",
    "ros-rolling-ament-cmake-export-include-directories",
    "ros-rolling-ament-cmake-export-interfaces",
    "ros-rolling-ament-cmake-export-libraries",
    "ros-rolling-ament-cmake-export-link-flags",
    "ros-rolling-ament-cmake-export-targets",
    "ros-rolling-ament-cmake-flake8",
    "ros-rolling-ament-cmake-gen-version-h",
    "ros-rolling-ament-cmake-gmock",
    "ros-rolling-ament-cmake-gtest",
    "ros-rolling-ament-cmake-include-directories",
    "ros-rolling-ament-cmake-libraries",
    "ros-rolling-ament-cmake-lint-cmake",
    "ros-rolling-ament-cmake-pep257",
    "ros-rolling-ament-cmake-pytest",
    "ros-rolling-ament-cmake-python",
    "ros-rolling-ament-cmake-ros",
    "ros-rolling-ament-cmake-target-dependencies",
    "ros-rolling-ament-cmake-test",
    "ros-rolling-ament-cmake-uncrustify",
    "ros-rolling-ament-cmake-version",
    "ros-rolling-ament-cmake-xmllint",
    "ros-rolling-ament-cmake",
    "ros-rolling-ament-copyright",
    "ros-rolling-ament-cppcheck",
    "ros-rolling-ament-cpplint",
    "ros-rolling-ament-flake8",
    "ros-rolling-ament-index-cpp",
    "ros-rolling-ament-index-python",
    "ros-rolling-ament-lint-auto",
    "ros-rolling-ament-lint-cmake",
    "ros-rolling-ament-lint-common",
    "ros-rolling-ament-lint",
    "ros-rolling-ament-package",
    "ros-rolling-ament-pep257",
    "ros-rolling-ament-uncrustify",
    "ros-rolling-ament-xmllint",
    "ros-rolling-angles",
    "ros-rolling-builtin-interfaces",
    "ros-rolling-class-loader",
    "ros-rolling-common-interfaces",
    "ros-rolling-composition-interfaces",
    "ros-rolling-composition",
    "ros-rolling-console-bridge-vendor",
    "ros-rolling-cv-bridge",
    "ros-rolling-demo-nodes-cpp-native",
    "ros-rolling-demo-nodes-cpp",
    "ros-rolling-demo-nodes-py",
    "ros-rolling-depthimage-to-laserscan",
    "ros-rolling-desktop",
    "ros-rolling-diagnostic-msgs",
    "ros-rolling-domain-coordinator",
    "ros-rolling-dummy-map-server",
    "ros-rolling-dummy-robot-bringup",
    "ros-rolling-dummy-sensors",
    "ros-rolling-eigen3-cmake-module",
    "ros-rolling-example-interfaces",
    "ros-rolling-examples-rclcpp-minimal-action-client",
    "ros-rolling-examples-rclcpp-minimal-action-server",
    "ros-rolling-examples-rclcpp-minimal-client",
    "ros-rolling-examples-rclcpp-minimal-composition",
    "ros-rolling-examples-rclcpp-minimal-publisher",
    "ros-rolling-examples-rclcpp-minimal-service",
    "ros-rolling-examples-rclcpp-minimal-subscriber",
    "ros-rolling-examples-rclcpp-minimal-timer",
    "ros-rolling-examples-rclcpp-multithreaded-executor",
    "ros-rolling-examples-rclpy-executors",
    "ros-rolling-examples-rclpy-minimal-action-client",
    "ros-rolling-examples-rclpy-minimal-action-server",
    "ros-rolling-examples-rclpy-minimal-client",
    "ros-rolling-examples-rclpy-minimal-publisher",
    "ros-rolling-examples-rclpy-minimal-service",
    "ros-rolling-examples-rclpy-minimal-subscriber",
    "ros-rolling-fastcdr",
    "ros-rolling-fastrtps-cmake-module",
    "ros-rolling-fastrtps",
    "ros-rolling-foonathan-memory-vendor",
    "ros-rolling-geometry-msgs",
    "ros-rolling-geometry2",
    "ros-rolling-gmock-vendor",
    "ros-rolling-gtest-vendor",
    "ros-rolling-ignition-cmake2-vendor",
    "ros-rolling-ignition-math6-vendor",
    "ros-rolling-image-geometry",
    "ros-rolling-image-tools",
    "ros-rolling-image-transport",
    "ros-rolling-interactive-markers",
    "ros-rolling-intra-process-demo",
    "ros-rolling-joy",
    "ros-rolling-kdl-parser",
    "ros-rolling-keyboard-handler",
    "ros-rolling-laser-geometry",
    "ros-rolling-launch-ros",
    "ros-rolling-launch-testing-ament-cmake",
    "ros-rolling-launch-testing-ros",
    "ros-rolling-launch-testing",
    "ros-rolling-launch-xml",
    "ros-rolling-launch-yaml",
    "ros-rolling-launch",
    "ros-rolling-libcurl-vendor",
    "ros-rolling-libstatistics-collector",
    "ros-rolling-libyaml-vendor",
    "ros-rolling-lifecycle-msgs",
    "ros-rolling-lifecycle",
    "ros-rolling-logging-demo",
    "ros-rolling-map-msgs",
    "ros-rolling-mcap-vendor",
    "ros-rolling-message-filters",
    "ros-rolling-nav-msgs",
    "ros-rolling-orocos-kdl-vendor",
    "ros-rolling-osrf-pycommon",
    "ros-rolling-pcl-conversions",
    "ros-rolling-pcl-msgs",
    "ros-rolling-pendulum-control",
    "ros-rolling-pendulum-msgs",
    "ros-rolling-pluginlib",
    "ros-rolling-pybind11-vendor",
    "ros-rolling-python-cmake-module",
    "ros-rolling-python-qt-binding",
    "ros-rolling-qt-dotgraph",
    "ros-rolling-qt-gui-cpp",
    "ros-rolling-qt-gui-py-common",
    "ros-rolling-qt-gui",
    "ros-rolling-quality-of-service-demo-cpp",
    "ros-rolling-quality-of-service-demo-py",
    "ros-rolling-rcl-action",
    "ros-rolling-rcl-interfaces",
    "ros-rolling-rcl-lifecycle",
    "ros-rolling-rcl-logging-interface",
    "ros-rolling-rcl-logging-spdlog",
    "ros-rolling-rcl-yaml-param-parser",
    "ros-rolling-rcl",
    "ros-rolling-rclcpp-action",
    "ros-rolling-rclcpp-components",
    "ros-rolling-rclcpp-lifecycle",
    "ros-rolling-rclcpp",
    "ros-rolling-rclpy",
    "ros-rolling-rcpputils",
    "ros-rolling-rcutils",
    "ros-rolling-resource-retriever",
    "ros-rolling-rmw-dds-common",
    "ros-rolling-rmw-fastrtps-cpp",
    "ros-rolling-rmw-fastrtps-shared-cpp",
    "ros-rolling-rmw-implementation-cmake",
    "ros-rolling-rmw-implementation",
    "ros-rolling-rmw",
    "ros-rolling-robot-state-publisher",
    "ros-rolling-ros-base",
    "ros-rolling-ros-core",
    "ros-rolling-ros-environment",
    "ros-rolling-ros-workspace",
    "ros-rolling-ros2action",
    "ros-rolling-ros2bag",
    "ros-rolling-ros2cli-common-extensions",
    "ros-rolling-ros2cli",
    "ros-rolling-ros2component",
    "ros-rolling-ros2doctor",
    "ros-rolling-ros2interface",
    "ros-rolling-ros2launch",
    "ros-rolling-ros2lifecycle",
    "ros-rolling-ros2multicast",
    "ros-rolling-ros2node",
    "ros-rolling-ros2param",
    "ros-rolling-ros2pkg",
    "ros-rolling-ros2run",
    "ros-rolling-ros2service",
    "ros-rolling-ros2topic",
    "ros-rolling-rosbag2-compression-zstd",
    "ros-rolling-rosbag2-compression",
    "ros-rolling-rosbag2-cpp",
    "ros-rolling-rosbag2-interfaces",
    "ros-rolling-rosbag2-py",
    "ros-rolling-rosbag2-storage-default-plugins",
    "ros-rolling-rosbag2-storage-mcap",
    "ros-rolling-rosbag2-storage-sqlite3",
    "ros-rolling-rosbag2-storage",
    "ros-rolling-rosbag2-transport",
    "ros-rolling-rosbag2",
    "ros-rolling-rosgraph-msgs",
    "ros-rolling-rosidl-adapter",
    "ros-rolling-rosidl-cli",
    "ros-rolling-rosidl-cmake",
    "ros-rolling-rosidl-core-generators",
    "ros-rolling-rosidl-core-runtime",
    "ros-rolling-rosidl-default-generators",
    "ros-rolling-rosidl-default-runtime",
    "ros-rolling-rosidl-dynamic-typesupport-fastrtps",
    "ros-rolling-rosidl-dynamic-typesupport",
    "ros-rolling-rosidl-generator-c",
    "ros-rolling-rosidl-generator-cpp",
    "ros-rolling-rosidl-generator-py",
    "ros-rolling-rosidl-generator-type-description",
    "ros-rolling-rosidl-parser",
    "ros-rolling-rosidl-pycommon",
    "ros-rolling-rosidl-runtime-c",
    "ros-rolling-rosidl-runtime-cpp",
    "ros-rolling-rosidl-runtime-py",
    "ros-rolling-rosidl-typesupport-c",
    "ros-rolling-rosidl-typesupport-cpp",
    "ros-rolling-rosidl-typesupport-fastrtps-c",
    "ros-rolling-rosidl-typesupport-fastrtps-cpp",
    "ros-rolling-rosidl-typesupport-interface",
    "ros-rolling-rosidl-typesupport-introspection-c",
    "ros-rolling-rosidl-typesupport-introspection-cpp",
    "ros-rolling-rpyutils",
    "ros-rolling-rqt-action",
    "ros-rolling-rqt-bag-plugins",
    "ros-rolling-rqt-bag",
    "ros-rolling-rqt-common-plugins",
    "ros-rolling-rqt-console",
    "ros-rolling-rqt-graph",
    "ros-rolling-rqt-gui-cpp",
    "ros-rolling-rqt-gui-py",
    "ros-rolling-rqt-gui",
    "ros-rolling-rqt-image-view",
    "ros-rolling-rqt-msg",
    "ros-rolling-rqt-plot",
    "ros-rolling-rqt-publisher",
    "ros-rolling-rqt-py-common",
    "ros-rolling-rqt-py-console",
    "ros-rolling-rqt-reconfigure",
    "ros-rolling-rqt-service-caller",
    "ros-rolling-rqt-shell",
    "ros-rolling-rqt-srv",
    "ros-rolling-rqt-topic",
    "ros-rolling-rttest",
    "ros-rolling-rviz-assimp-vendor",
    "ros-rolling-rviz-common",
    "ros-rolling-rviz-default-plugins",
    "ros-rolling-rviz-ogre-vendor",
    "ros-rolling-rviz-rendering",
    "ros-rolling-rviz2",
    "ros-rolling-sdl2-vendor",
    "ros-rolling-sensor-msgs-py",
    "ros-rolling-sensor-msgs",
    "ros-rolling-service-msgs",
    "ros-rolling-shape-msgs",
    "ros-rolling-shared-queues-vendor",
    "ros-rolling-spdlog-vendor",
    "ros-rolling-sqlite3-vendor",
    "ros-rolling-sros2-cmake",
    "ros-rolling-sros2",
    "ros-rolling-statistics-msgs",
    "ros-rolling-std-msgs",
    "ros-rolling-std-srvs",
    "ros-rolling-stereo-msgs",
    "ros-rolling-tango-icons-vendor",
    "ros-rolling-teleop-twist-joy",
    "ros-rolling-teleop-twist-keyboard",
    "ros-rolling-tf2-bullet",
    "ros-rolling-tf2-eigen-kdl",
    "ros-rolling-tf2-eigen",
    "ros-rolling-tf2-geometry-msgs",
    "ros-rolling-tf2-kdl",
    "ros-rolling-tf2-msgs",
    "ros-rolling-tf2-py",
    "ros-rolling-tf2-ros-py",
    "ros-rolling-tf2-ros",
    "ros-rolling-tf2-sensor-msgs",
    "ros-rolling-tf2-tools",
    "ros-rolling-tf2",
    "ros-rolling-tinyxml-vendor",
    "ros-rolling-tinyxml2-vendor",
    "ros-rolling-tlsf-cpp",
    "ros-rolling-tlsf",
    "ros-rolling-topic-monitor",
    "ros-rolling-tracetools",
    "ros-rolling-trajectory-msgs",
    "ros-rolling-turtlesim",
    "ros-rolling-type-description-interfaces",
    "ros-rolling-uncrustify-vendor",
    "ros-rolling-unique-identifier-msgs",
    "ros-rolling-urdf-parser-plugin",
    "ros-rolling-urdf",
    "ros-rolling-urdfdom-headers",
    "ros-rolling-urdfdom",
    "ros-rolling-visualization-msgs",
    "ros-rolling-yaml-cpp-vendor",
    "ros-rolling-zstd-vendor",
]

[sources]

[sources.ports]
url = "https://mirrors.ustc.edu.cn/ubuntu-ports"
sections = [
    "main",
    "universe",
]

[sources.ros2]
url = "http://packages.ros.org/ros2/ubuntu"
sections = [
    "main",
]
